flowerNames = [
    'Sunflower', 
    'Poppy', 
    'Pansy', 
    'Violet', 
    'Hyacinth',
    'Anemone', 
    'Gladiolus', 
    'Forget-me-not', 
    'Virginia Bluebells',
    'Bougainvillea', 
    'Christmas Cactus', 
    'Camellia',
    'Chrysanthemum', 
    'Crocus', 
    'Dahlia', 
    'Foxglove',
    'Geranium', 
    'Gerbera Daisy', 
    'Honeysuckle vine',
    'Hop Tree', 
    'Lilac', 
    'Lotus', 
    'Magnolia Tree',
    'Morning Glory', 
    'Peony', 
    'Primrose', 
    'Snapdragon',
    'Snowdrop', 
    'Tuberous Begonia', 
    'Moss rose', 
    'Hydrangea'
]