# flowerNames = [
#     'Sunflower', 
#     'Poppy', 
#     'Pansy', 
#     'Violet', 
#     'Hyacinth',
#     'Anemone', 
#     'Gladiolus', 
#     'Forget-me-not', 
#     'Virginia Bluebells',
#     'Bougainvillea', 
#     'Christmas Cactus', 
#     'Camellia',
#     'Chrysanthemum', 
#     'Crocus', 
#     'Dahlia', 
#     'Foxglove',
#     'Geranium', 
#     'Gerbera Daisy',
#     'Hop Tree', 
#     'Lilac', 
#     'Lotus', 
#     'Magnolia Tree',
#     'Morning Glory', 
#     'Peony', 
#     'Primrose', 
#     'Snapdragon',
#     'Tuberous Begonia', 
#     'Moss rose',
# ]

flowerNames = [
    'Shasta Daisy',
    'Hybrid Tea Rose',
    'Daffodil',
    'Tulip',
    'Lily', 
    'Hardy Hibiscus', 
    'Jasmine', 
    'Lavender',
    'Hydrangea'
]